### ISSUE TITLE
Podcast value in API but not in feed

### ISSUE THREAD

**Issue by ibz** [Podcastindex-org/api#2]
I noticed that some podcasts have a `value` tag returned by the API even though this does not appear in the original feed.

I understand that this happens because the podcaster added the feed in Podcaster Wallet but did not bother (or could not) update the original feed.

Now the question is, how to deal with this issue in my podcast client? Let's say I update every feed periodically from the original source - should I also hit the PodcastIndex API just to see whether a `value` tag appeared here or whether it changed? (because it could happen, right?) Is there a better way? This seems like a bad approach, but I can't see a better one for this case unfortunately. Perhaps to only hit the API if there was a new item in the feed?

**Comment by daveajones** [comment]
You have the right understanding.  Until the day when hosting companies start allowing the value block to be inserted through their UI we're stuck with the API approach.  From what I've seen, most apps are just pinging us for a data refresh when a new episode hits or when the users explicitly asks the UI for a refresh.

Not really any other options at this point.

**Comment by ibz** [comment]
Great. I'll close the issue. It's good to have this written down anyway, in case anyone else hits this problem. Thanks!
